[package]
name = "dfu-flasher"
version = "0.1.0"
authors = ["mikael <mike7b4@protonmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
nix = ""
#usbapi = {"git" = "https://gitlab.com/mike7b4/usbapi-rs"}

usbapi = {"path" = "../../usbapi-rs"}
